name: External triggered Workflow
on:
  repository_dispatch:
    types: [custom_event]

jobs:
   run-dispatch:
      runs-on: ${{ vars.COMMON_SMALL }}

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Test Commands
          run: echo "Workflow triggered by another event"